const GET_CATALOG = 'GET_CATALOG';
const GET_RECOMMANDATION = 'GET_RECOMMANDATION';
const POST_ORDER = 'POST_ORDER';
const POST_REWARD = 'POST_REWARD';

export {
  GET_CATALOG, POST_ORDER, GET_RECOMMANDATION, POST_REWARD,
};
